import styles from '../../styles/display.module.css';
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'


function DisplayProducts({ electronics }) {
    return (
        <>
            <Head>
                <title>Shopify</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.head}>These are the available Electronic gadgets</h1>
            <div className={styles.cards}>
                {electronics.map((electronic) => {
                    return (
                        <Link key={electronic.id} href={`/electronics/${electronic.id}`} passHref>
                            <div className={styles.card}>
                                <div className={styles.image}>
                                    <img src={electronic.image} alt="Image" width="100%" height="200px" />
                                </div>
                                <div className={styles.details}>
                                    <h3>{electronic.title}</h3>
                                    <p>${electronic.price}</p>
                                    {/* <p>{electronic.category}</p>
                                <p>{electronic.description}</p> */}
                                </div>
                            </div>
                        </Link>
                    )
                })}
            </div>

        </>
    )
}

export async function getStaticProps() {
    const response = await fetch('https://fakestoreapi.com/products/category/electronics')
    const data = await response.json();

    return {
        props: {
            electronics: data,
        }
    }

}

export default DisplayProducts;