import styles from '../../styles/display.module.css';
import Head from 'next/head'
import Electronic from '../../components/Electronic/Electronic'
import Footer from '../../components/Jewelery/Layout/Footer';
import MainNav from '../../components/Jewelery/Layout/MainNav';


function DisplayProducts({ electronics }) {
    return (
        <>
            <Head>
                <title>Shopify || Electronics</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainNav />

            <h1 className={styles.head}>These are the available Electronic gadgets</h1>
            <div className={styles.cards}>
                {electronics.map((electronic) => (
                    <Electronic key={electronic.id} electronic={electronic} />
                ))}
            </div>

            <div>
                <Footer />
            </div>
        </>
    )
}


export async function getStaticProps() {
    const data = await fetch('https://fakestoreapi.com/products/category/electronics').then(data => data.json())
    return {
        props: {
            electronics: data,
        }
    }
}

export default DisplayProducts;