import styles from '../../styles/display.module.css';
import Head from 'next/head'
import classes from '../../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'


function DisplayProducts({ electronics }) {

    return (
        <>
            <Head>
                <title>Shopify</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={classes.header}>
                <div className={classes.nav}>
                    {/* <img src="" alt="logo" /> */}
                    <Image src="/image.jpg" alt="Logo" width="100%" height="100%" />
                </div>

                <div>
                    <nav className={classes.links}>
                        <Link href="/electronics">
                            <a className={classes.subnav}>Electronics</a>
                        </Link>
                        <Link href="/jewelery">
                            <a className={classes.subnav}>Jewelery</a>
                        </Link>
                        <Link href='/men'>
                            <a className={classes.subnav}>For Men</a>
                        </Link>
                        <Link href='/women'>
                            <a className={classes.subnav}>For Women</a>
                        </Link>
                    </nav>
                </div>

                <div>
                    Contact Us
                </div>
            </header>

            <h1 className={styles.head}>These are the available Electronic gadgets</h1>
            <div className={styles.cards}>
                {electronics.map((electronic) => {
                    return (
                        <Link key={electronic.id} href={`/electronics/${electronic.id}`} passHref>
                            <div className={styles.card}>
                                <div className={styles.image}>
                                    <img src={electronic.image} alt="Image" width="100%" height="200px" />
                                </div>
                                <div className={styles.details}>
                                    <h3>{electronic.title}</h3>
                                    <p>${electronic.price}</p>
                                    {/* <p>{electronic.category}</p>
                                <p>{electronic.description}</p> */}
                                </div>
                            </div>
                        </Link>
                    )
                })}
            </div>

        </>
    )
}

export async function getStaticProps() {
    const response = await fetch('https://fakestoreapi.com/products/category/electronics')
    const data = await response.json();

    return {
        props: {
            electronics: data,
        }
    }

}

export default DisplayProducts;