import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomePage from '../components/HomePage/HomePage'
import Services from '../components/Services/Services'
import Feedbacks from '../components/Feedback/Feedbacks'
import Hero from '../components/Hero/Hero'
import Sponsors from '../components/Sponsors/Sponsors'
import Gallery from '../components/Galleries/Gallery'
import MainNav from '../components/Jewelery/Layout/MainNav'
import Footer from '../components/Jewelery/Layout/Footer'

export default function Home({ products }) {

  let sliced = products.slice(1, 9)

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainNav />

      <main className={styles.main}>

        <Hero />

        <div className={styles.display}>
          <h3 className={styles.head}>Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Doloremque corrupti explicabo quas quisquam cupiditate quaerat necessitatibus eius voluptates
            provident voluptatum.</h3>
          <p className={styles.texts}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi, nisi!</p>

          <h2 className={styles.texts}>Our Products at a Glance</h2>
          <div className={styles.cards}>
            {sliced.map((product) => (
              <HomePage key={product.id} product={product} />
            ))}
          </div>
        </div>

        <div className={styles.containers}>
          <Services />
        </div>

        <div>
          <Feedbacks />
        </div>

        <div>
          <Sponsors />
        </div>

        <div>
          <Gallery />
        </div>
      </main>

      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const data = await fetch('https://fakestoreapi.com/products').then(data => data.json())
  return {
    props: {
      products: data,
    }
  }
}