import styles from '../../styles/display.module.css';
import Head from 'next/head'
import Women from '../../components/Women/Women'
import Footer from '../../components/Jewelery/Layout/Footer';
import MainNav from '../../components/Jewelery/Layout/MainNav';


function DisplayProducts({ women }) {
    return (
        <>
            <Head>
                <title>Shopify || Women</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainNav />

            <h1 className={styles.head}>These are the available Electronic gadgets</h1>
            <div className={styles.cards}>
                {women.map((women) => (
                    <Women key={women.id} women={women} />
                ))}
            </div>

            <div>
                <Footer />
            </div>
        </>
    )
}


export async function getStaticProps() {
    const data = await fetch(`https://fakestoreapi.com/products/category/women's%20clothing`).then(data => data.json())
    return {
        props: {
            women: data,
        }
    }
}

export default DisplayProducts;